version: '3'

services:
    nest:
        build: .
        command: npm run start:dev
        volumes:
            - .:/code
        ports:
            - "3000:3000"
networks:
    default:
        external:
            name: api
